### ISSUE TITLE
Tab navigation component

### ISSUE THREAD

**Issue by raymondchiu10** [AliceHsieh/baymax#2]
Build the component for tab navigation in both the header and footer. Represented by a dynamically generated array of buttons.

**Comment by JERRYJURR** [comment]
![screen shot 2019-02-16 at 9 40 03 am](https://user-images.githubusercontent.com/35520333/52903208-07c73d80-31cf-11e9-9aac-c3f7ec7a9906.png)


```
position: absolute;
width: 61px;
height: 28px;
left: 293px;
top: 383px;

font-family: Anchor;
font-style: normal;
font-weight: 500;
line-height: normal;
font-size: 24px;
text-align: center;

color: #FBAE34;

```
